// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKmThViYYfzqAbYRrmebB08DNZUnL4-1Y',
    appId: '1:362700306314:web:00db0185935ed43d87fa73',
    messagingSenderId: '362700306314',
    projectId: 'nationofdelivery-abd39',
    authDomain: 'nationofdelivery-abd39.firebaseapp.com',
    storageBucket: 'nationofdelivery-abd39.appspot.com',
    measurementId: 'G-QN4VJVJXTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBRhP6PY6zcdzfTaxDn3X0JC36TQ3BFw',
    appId: '1:362700306314:android:970f609fa558c68287fa73',
    messagingSenderId: '362700306314',
    projectId: 'nationofdelivery-abd39',
    storageBucket: 'nationofdelivery-abd39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0DO3EQV8UfEQ0IyO9Kad3NiSdL8Ruq4',
    appId: '1:362700306314:ios:e51165850ab8552587fa73',
    messagingSenderId: '362700306314',
    projectId: 'nationofdelivery-abd39',
    storageBucket: 'nationofdelivery-abd39.appspot.com',
    iosClientId: '362700306314-e3mbj2mjvok20rv8s994d7dliqs706sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNationOfDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0DO3EQV8UfEQ0IyO9Kad3NiSdL8Ruq4',
    appId: '1:362700306314:ios:e26355528be0aaa987fa73',
    messagingSenderId: '362700306314',
    projectId: 'nationofdelivery-abd39',
    storageBucket: 'nationofdelivery-abd39.appspot.com',
    iosClientId: '362700306314-g33r8s686bfs85oqvrqar51khf5097i0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNationOfDelivery.RunnerTests',
  );
}
